version: '3'

services:

  neo4j:
    image: vladbatushkov/neo4j-flights:latest
    ports:
      - 7474:7474
      - 7687:7687
  #   environment:
  #     - NEO4J_dbms_security_procedures_unrestricted=apoc.*
  #     - NEO4J_apoc_import_file_enabled=true
  #     - NEO4J_apoc_export_file_enabled=true
  #     - NEO4J_dbms_shell_enabled=true

  api:
    build: ./api
    ports:
      - 4001:4001
    links:
    - neo4j
    depends_on:
    - neo4j

  # ui:
  #   build: ./ui
  #   ports:
  #     - 3000:3000
  #   links:
  #   - api
  #   depends_on:
  #   - api
